# SITE CONFIGURATION
baseurl: ""
url: "https://servitubos.es"
title: Ponga fin a sus problemas de atascos y fugas # site's title
description: "Localizace y ponga fin a sus problemas de atascos y fugas en tuberías de desagües" # used by search engines

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: serviTubos # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: "3990963d564f97198086796f6bda1833" # Email MD5 hash

  # Header and footer text
  header_text: Localice y ponga fin a problemas de atascos y fugas en tuberías de desagües
  footer_text: >
    Juan Ortiz. Nº Colegiado 1182 COAATCAN. Santander.  Tlfn. 667 888 398

  # Icons
  email_address: "coaatcan1182@gmail.com" # Full email address, e.g. "sam@example.com"
  google_analytics: # Tracking ID, e.g. "UA-000000-01"

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
